apiVersion: v1
kind: Service
metadata:
  labels:
    app: sobesity
  name: sobesity-svc-dev
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: sobesity-dev
